name: Slack Integration

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  issues:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  slack-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/slack-integration@v1
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: "C054MTB7FHD"
          subscribe-pulls: true
          subscribe-issues: true
          subscribe-reviews: true
          subscribe-pull-comments: true
          subscribe-issue-comments: true
          threading-comments: true
          footer: "<@U04602RGKRR>"

      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{secrets.MEMBER_MAP[github.event.pull_request.requested_reviewers[0]]}}
        run: echo "$GITHUB_CONTEXT"
