name: Slack Integration

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  pull_request_review:
    types: [submitted]

jobs:
  slack-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/slack-integration@v1
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: "C054MTB7FHD"
          subscribe-pulls: true
          subscribe-reviews: true
          subscribe-pull-comments: true
          threading-comments: true
          footer: ${{ github.event.pull_request.assignee.login }} from review request ${{ github.event.pull_request.requested_reviewers[0].login }}
