name: "pull-request-workflow"

on:
  pull_request:
    types:
      [opened, edited, closed, reopened, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issue_comment:
    types: [created, edited, deleted]
  schedule:
    - cron: "0 10 * * 1-5"

jobs:
  pull_request_workflow:
    runs-on: ubuntu-latest
    name: A job that notifies slack on PR events
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run pull request workflow
        uses: cakarci/pull-request-workflow@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: "C054MTB7FHD"
